=== nour-el-houda/TP2/etudiants.dtd
<!ELEMENT etudiants (etudiant*)>
<!ELEMENT etudiant (identite)>
<!ELEMENT identite (matricule,nom,prenom,moy,credit,Uniteacuise)>
<!ELEMENT moy (moyS1,moyS2,moyannuel)>
<!ELEMENT credit (creditS1,creditS2)>
<!ELEMENT moyS1 (#PCDATA)>
<!ELEMENT moyS2 (#PCDATA)>
<!ELEMENT creditS1 (#PCDATA)>
<!ELEMENT creditS2 (#PCDATA)>
<!ELEMENT moyannuel (#PCDATA)>
<!ELEMENT matricule (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT Uniteacuise (#PCDATA)>

=== nour-el-houda/TP2/etudiants.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/css" href="etudiants.css"?>
<!DOCTYPE etudiants SYSTEM "file:///C:/Users/NOUR%20ELHOUDA/Desktop/Tp2MTI/Travaille%20a%20domicile%20Tp2/etudiants.dtd">
<etudiants>
    <etudiant>
      <identite>
       <matricule>Q14M121</matricule>
       <nom>ZIANE</nom>
       <prenom>BILAL</prenom>
       <moy>
         <moyS1>12.78</moyS1>
         <moyS2></moyS2>
         <moyannuel>12.83</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
    <identite>
       <matricule>Q14M120</matricule>
       <nom>ZITOUNI</nom>
       <prenom>SOUMIA</prenom>
       <moy>
         <moyS1>12.01</moyS1>
         <moyS2>13.45</moyS2>
         <moyannuel>12.73</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M125</matricule>
       <nom>ZEGHDANE</nom>
       <prenom>HOUSSAM</prenom>
       <moy>
         <moyS1>13.63</moyS1>
         <moyS2>11.52</moyS2>
         <moyannuel>12.58</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M122</matricule>
       <nom>ZIANE</nom>
       <prenom>MEZIANE</prenom>
       <moy>
         <moyS1>12.72</moyS1>
         <moyS2>11.93</moyS2>
         <moyannuel>12.33</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M152</matricule>
       <nom>TALEB</nom>
       <prenom>ASMA</prenom>
       <moy>
         <moyS1>14.73</moyS1>
         <moyS2>9.90</moyS2>
         <moyannuel>12.32</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>21</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M141</matricule>
       <nom>TOUATI</nom>
       <prenom>MOHAMED</prenom>
       <moy>
         <moyS1>11.99</moyS1>
         <moyS2>10.37</moyS2>
         <moyannuel>11.18</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M126</matricule>
       <nom>ZEGADI</nom>
       <prenom>AMEL</prenom>
       <moy>
         <moyS1>11.04</moyS1>
         <moyS2>11.25</moyS2>
         <moyannuel>11.15</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M123</matricule>
       <nom>ZIANE</nom>
       <prenom>AMIRA</prenom>
       <moy>
         <moyS1>10.15</moyS1>
         <moyS2>11.91</moyS2>
         <moyannuel>11.03</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M135</matricule>
       <nom>YAHIAOUI</nom>
       <prenom>MOHAMED</prenom>
       <moy>
         <moyS1>11.32</moyS1>
         <moyS2>10.56</moyS2>
         <moyannuel>10.94</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M124</matricule>
       <nom>ZERARI</nom>
       <prenom>OUASSILA</prenom>
       <moy>
         <moyS1>10.20</moyS1>
         <moyS2>11.65</moyS2>
         <moyannuel>10.</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
     <identite>
       <matricule>Q14M168</matricule>
       <nom>SENANI</nom>
       <prenom>HAYET</prenom>
       <moy>
         <moyS1>12.70</moyS1>
         <moyS2>9.12</moyS2>
         <moyannuel>10.91</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>3</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
    <etudiant>
      <identite>
       <matricule>Q14M143</matricule>
       <nom>TIGRINE</nom>
       <prenom>AYOUB</prenom>
       <moy>
         <moyS1>11.30</moyS1>
         <moyS2>10.30</moyS2>
         <moyannuel>10.8</moyannuel>
       </moy>
       <credit>
         <creditS1>30</creditS1>
         <creditS2>30</creditS2>
       </credit>
       <Uniteacuise>oui</Uniteacuise>
      </identite>
    </etudiant>
 </etudiants>
